# Generated by Django 3.1.3 on 2020-12-03 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('gallery', '0002_auto_20201203_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=40)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtailimages.image')),
            ],
        ),
    ]
