# Generated by Django 3.1.3 on 2020-12-01 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='company_description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='mission',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='vision',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
